[project]
name = "w1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "playwright>=1.47.0",
    "pytest-playwright>=0.5.2",
    "rich>=13.8.1",
]
